import './globals.css'
import { Taviraj } from 'next/font/google'


const taviraj = Taviraj({ weight: '400', subsets: ['latin'], display: 'swap', })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={taviraj.className}>{children}</body>
    </html>
  )
}
